### ISSUE TITLE
POST request without trailing slash in URL is not working

### ISSUE THREAD

**Issue by mobichel** [arlejeun/sputnik#3]
When I try to do POST http://localhost:5000/api/pulse/dashboards
it fails with message:
`FormDataRoutingRedirect: A request was sent to this URL (http://localhost:5000/api/pulse/dashboards) but a redirect was issued automatically by the routing system to "http://localhost:5000/api/pulse/dashboards/".  The URL was defined with a trailing slash so Flask will automatically redirect to the URL with the trailing slash if it was accessed without one.  Make sure to directly send your POST-request to this URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.`

However POST with  http://localhost:5000/api/pulse/dashboards/ works OK.

**Comment by arlejeun** [comment]
Artyom,
Im traveling today and won't be able to update it. I've noticed it before for visualization. You want to remove the line

@viz_api.route('', methods=['POST'])
@http_auth_required
@admin_permission.require(http_exception=403)
Remove the line

@dashboard_api.route('', methods=['POST']) 
and I would suggest to keep same security 

@http_auth_required
@admin_permission.require(http_exception=403)

I was experiencing with visualization and didn't bring it to dashboard yet

**Comment by arlejeun** [comment]
Actually remove this line
@dashboard_api.route('/', methods=['POST'])

**Comment by arlejeun** [comment]
Artyom,
Im traveling today and won't be able to update it. I've noticed it before for visualization. See below what was done for the visualization API 
@viz_api.route('', methods=['POST'])
@http_auth_required
@admin_permission.require(http_exception=403)

Remove the following line from the dashboard API
@dashboard_api.route('/', methods=['POST']) 

and I would suggest to keep same security As the one for visualization as well.
@http_auth_required
@admin_permission.require(http_exception=403)

I will merge it later this weekend
