### ISSUE TITLE
Build production - Optimization

### ISSUE THREAD

**Issue by arlejeun** [arlejeun/sputnik#5]
I would like to optimize the network bandwidth used by the application and minify the js and html files.
I tried to used polymer build with the polymer.js file but I wasn't successful so far.

@mobichel  Can you help?

**Comment by mobichel** [comment]
@arlejeun , sure!

I will compare webpack vs polymer cli options to make minified build.

**Comment by mobichel** [comment]
@arlejeun
I see there are two index.html files:
static/index.html
templates/index.html
As I understood the first one is an entry point now it needs to be used for optimisation. 
What second index.html for?

**Comment by mobichel** [comment]
Ok, I see now. templates/index.html is used for templating. Think we can use landing-page.html and market-app.html as entry points for minification

**Comment by arlejeun** [comment]
Sorry I missed your questions. You're right! The one used for templating is the one propagating the user information and credentials from the server to the client.

**Comment by mobichel** [comment]
Created #6

**Comment by arlejeun** [comment]
Worked like a charm. Thanks @mobichel
