### ISSUE TITLE
Link style for s-html element

### ISSUE THREAD

**Issue by arlejeun** [arlejeun/sputnik#9]
Exploring the Web_Engagement_Summary_View dashboard, the link are defined in the definition of the dashboard as a <s-html> tag but I didn't manage to set the color of the link in purple.

@mobichel - Can you have a quick look?

**Comment by mobichel** [comment]
@arlejeun , would you like to apply purple (#5d3e5d) color to all links?
We can add common rule for all <a> elements in application:
a {
   color: #5d3e5d;
}

**Comment by mobichel** [comment]
#10

**Comment by arlejeun** [comment]
https://github.com/arlejeun/sputnik/commit/33979f78f8109958f5f6819aa05084996ddbad75
